homeassistant:
  customize:
    package.node_anchors:
      customize: &customize
        package: 'Air Conditioner Manager 1.0'
        author: 'LoTableT'
        reference: " https://github.com/lotablet/ha-package-air-conditioner-manager "
#
#   PREMESSA: 
#   - è neccessario avere home assistant AGGIORNATO all'ultima versione sennò le automazioni non funzioneranno.
#   - avere un sensore o piu sensori che rilevano l'apertura e chiusura di una o piu finestre
#
                            ####################
                            ### IMPOSTAZIONI ###
                            ####################
#
#
# SOSTITUISCI I VARI NOMI DEI SENSORI CON I TUOI SENSORI, I NOMI DA SOSTITUIRE SONO IN MAIUSCOLO
# PUOI ANCHE IMPOSTARE UNA FRASE PERSONALIZZATA SU ALEXA QUANDO VIENE SPENTO IL CONDIZIONATORE QUANDO VIENE RILEVATA UNA FINESTRA APERTA.
      setting:
        Sensore Finestra: &finestra "{% if is_state('binary_sensor.TUAFINESTRA', 'on') %} Aperta {% else %} Chiusa {% endif %}"
        
        Messaggio di alexa per finestre aperte: &messaggiospegni "Spengo il condizionatore perchè le finestra è aperta"
       
        
        Inserisci qui sotto il climatizzatore da controllare: &condizionatore
          - climate.TUOCONDIZIONATORE
       
        Inserisci qui sotto il media player di alexa: &alexa
          - media_player.TUOALEXA
#
#
#####################
## GRUPPO FINESTRE ##
#####################
#
#
# Questo è un binary sensor che comprende più finestre, sostituire i vari binary_sensor 
# (finestra1, finestra2, finestra3) con i nomi effettivi delle entità che si 
# vogliono nel gruppo.
#
# ATTENZIONE: ricorda di aggiungere "binary_sensor.gruppo_finestre" nella sezione
# IMPOSTAZIONI - SENSORE FINESTRA per utilizzare questo binary_sensor se si vuole usare il gruppo finestre
#
#
binary_sensor:
  - platform: template
    sensors:
      gruppo_finestre:
        friendly_name: 'Gruppo Finestre'
        device_class: window
        value_template: >
          {% set sensors = [states.binary_sensor.finestra1,
                            states.binary_sensor.finestra2,
                            states.binary_sensor.finestra3] %}
          {{ sensors | selectattr('state','eq','on') | list | count > 0 }}

#
#
#################################################################
###################### FINE DELLE IMPOSTAZIONI ##################
#################################################################
#
#
#############
## SENSORI ##
#############
#
#
sensor:
  - platform: template
    sensors:
      finestra:
        value_template: *finestra
#
#
#################
## AUTOMAZIONI ##
#################
#
#
automation:
- id: '6384648283658272658463394'
  alias: Package Gestione Clima - Clima con trigger finestra
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.finestra
      to: Aperta
      for:
        hours: 0
        minutes: 3
        seconds: 0
      id: finestra
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: *condizionatore
          state: dry
        - condition: state
          entity_id: *condizionatore
          state: cool
        - condition: state
          entity_id: *condizionatore
          state: heat
        - condition: state
          entity_id: *condizionatore
          state: auto
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: *condizionatore
              state: auto
            - condition: trigger
              id:
                - finestra
          sequence:
            - target:
                entity_id: *condizionatore
              action: climate.turn_off
              data: {}
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ open_action is defined and open_action|length > 0 }}"
                  sequence: []
            - wait_for_trigger:
                - platform: state
                  entity_id: sensor.finestra
                  to: Chiusa
              continue_on_timeout: false
            - delay: 12
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ close_action is defined and close_action|length > 0 }}"
                  sequence: []
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: auto
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Automatica"
    - choose:
        - conditions:
            - condition: state
              entity_id: *condizionatore
              state: dry
            - condition: trigger
              id:
                - finestra
          sequence:
            - target:
                entity_id: *condizionatore
              action: climate.turn_off
              data: {}
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ open_action is defined and open_action|length > 0 }}"
                  sequence: []
            - wait_for_trigger:
                - platform: state
                  entity_id: sensor.finestra
                  to: Chiusa
              continue_on_timeout: false
            - delay: 12
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ close_action is defined and close_action|length > 0 }}"
                  sequence: []
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: dry
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Deumidificatore "
    - choose:
        - conditions:
            - condition: state
              entity_id: *condizionatore
              state: cool
            - condition: trigger
              id:
                - finestra
          sequence:
            - target:
                entity_id: *condizionatore
              action: climate.turn_off
              data: {}
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ open_action is defined and open_action|length > 0 }}"
                  sequence: []
            - wait_for_trigger:
                - platform: state
                  entity_id: sensor.finestra
                  to: Chiusa
              continue_on_timeout: false
            - delay: 12
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ close_action is defined and close_action|length > 0 }}"
                  sequence: []
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: cool
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Freddo"
    - choose:
        - conditions:
            - condition: state
              entity_id: *condizionatore
              state: heat
            - condition: trigger
              id:
                - finestra
          sequence:
            - target:
                entity_id: *condizionatore
              action: climate.turn_off
              data: {}
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ open_action is defined and open_action|length > 0 }}"
                  sequence: []
            - wait_for_trigger:
                - platform: state
                  entity_id: sensor.finestra
                  to: Chiusa
              continue_on_timeout: false
            - delay: 12
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ close_action is defined and close_action|length > 0 }}"
                  sequence: []
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: heat
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Caldo"
- id: '6384648283658272658463390'
  alias: Package Gestione Clima - Clima Gia Acceso
  description: ""
  trigger:
    - platform: state
      entity_id:
        *condizionatore
      to: dry
      for:
        hours: 0
        minutes: 0
        seconds: 10
      id: dry
    - platform: state
      entity_id:
        *condizionatore
      to: cool
      for:
        hours: 0
        minutes: 0
        seconds: 10
      id: cool
    - platform: state
      entity_id:
        *condizionatore
      for:
        hours: 0
        minutes: 0
        seconds: 10
      id: auto
      to: auto
    - platform: state
      entity_id:
        *condizionatore
      to: heat
      for:
        hours: 0
        minutes: 0
        seconds: 10
      id: heat
  condition:
    - condition: not
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: sensor.finestra
              state: Chiusa
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - dry
          sequence:
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - wait_for_trigger:
                - platform: state
                  entity_id:
                    - sensor.finestra
                  to: Chiusa
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: dry
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Deumidificatore "
    - choose:
        - conditions:
            - condition: trigger
              id:
                - cool
          sequence:
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  - climate.condizionatore_virtuale
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - wait_for_trigger:
                - platform: state
                  entity_id:
                    - sensor.finestra
                  to: Chiusa
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: cool
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Freddo "
    - choose:
        - conditions:
            - condition: trigger
              id:
                - auto
          sequence:
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - wait_for_trigger:
                - platform: state
                  entity_id:
                    - sensor.finestra
                  to: Chiusa
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: auto
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Automatica "
    - choose:
        - conditions:
            - condition: trigger
              id:
                - heat
          sequence:
            - action: notify.alexa_media
              data:
                target: *alexa
                message: *messaggiospegni
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  *condizionatore
            - wait_for_trigger:
                - platform: state
                  entity_id:
                    - sensor.finestra
                  to: Chiusa
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: climate.set_hvac_mode
              metadata: {}
              data:
                hvac_mode: heat
              target:
                entity_id: *condizionatore
            - action: notify.alexa_media
              data:
                target: *alexa
                message: "Riaccendo il condizionatore in modalità Caldo"
  mode: single
